# Generated by Django 2.2.5 on 2019-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
