# Generated by Django 2.2.5 on 2019-09-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20190917_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='result',
            field=models.ImageField(blank=True, upload_to='result'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmin', models.IntegerField()),
                ('ymax', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('class_name', models.IntegerField()),
                ('class_name_fa', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.File')),
            ],
        ),
    ]
