# Generated by Django 2.2.5 on 2019-09-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_auto_20190920_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='class_name_fa',
        ),
    ]
