# Generated by Django 2.2.5 on 2019-09-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0007_remove_category_class_name_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='class_name_fa',
            field=models.CharField(default='', max_length=100),
        ),
    ]
