# Generated by Django 2.2.5 on 2019-09-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_category_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description_fa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
