# Generated by Django 2.2.5 on 2019-09-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_auto_20190922_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='area',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='xmax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='xmin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='ymax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='ymin',
            field=models.FloatField(),
        ),
    ]
