# Generated by Django 2.2.5 on 2019-09-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_auto_20190922_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='xmax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='xmin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='ymax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='ymin',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
